language: csharp

sudo: false  # use the new container-based Travis infrastructure
dotnet: 2.1.4
dist: trusty

before_script:
  - nvm install lts
  - nvm use lts

cache:
  yarn: true

script:
  - ./build.sh Build